# Generated by Django 4.0.3 on 2022-04-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandeco', models.CharField(choices=[('CENTRAL', 'CENTRAL'), ('QUÍMICA', 'QUÍMICA'), ('FÍSICA', 'FÍSICA'), ('PREFEITURA', 'PREFEITURA')], max_length=120)),
                ('situation', models.CharField(max_length=120)),
                ('velocity', models.CharField(max_length=120)),
                ('last_atualization', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
