# Generated by Django 2.2.24 on 2022-03-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandeco', models.CharField(choices=[('C', 'CENTRAL'), ('Q', 'QUÍMICA'), ('F', 'FÍSICA'), ('P', 'PREFEITURA')], max_length=1)),
                ('situation', models.CharField(max_length=120)),
                ('velocity', models.CharField(max_length=120)),
                ('last_atualization', models.TimeField(auto_now=True)),
            ],
        ),
    ]
