# Generated by Django 2.2.24 on 2022-03-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fila',
            name='last_atualization',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
