# Generated by Django 2.2.24 on 2022-03-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0003_auto_20220328_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fila',
            name='bandeco',
            field=models.CharField(choices=[('CENTRAL', 'CENTRAL'), ('QUÍMICA', 'QUÍMICA'), ('FÍSICA', 'FÍSICA'), ('PREFEITURA', 'PREFEITURA')], max_length=120),
        ),
    ]
